### ISSUE TITLE
Feature: custom names for IAM Role and CloudWath log

### ISSUE THREAD

**Issue by Gershon-A** [coralogix/terraform-coralogix-aws#155]
Hello!
I'm deploying to different regions.
Can we have customizable IAM Role and CloudWatch log group names?
Thank's

**Comment by guyrenny** [comment]
Hi @Gershon-A , can you please let me know what is the module you are referring to (coralogix-aws-shipper, firehose, ...)?

**Comment by Gershon-A** [comment]
@guyrenny Hello
sorry for delay.
In my case the module is `cloudwatch_firehose_metrics_coralogix` , but this seems true for others as well.

**Comment by ryantanjunming** [comment]
Hi @Gershon-A, which role names in particular and how would they be grouped

I've named most of the aws_iam_role and loggroups to be synonymous with the supporting resource like the firehose stream name e.g. `var.firehose_stream` so that value can be name according to the region.

**Comment by ryantanjunming** [comment]
fixed with https://github.com/coralogix/terraform-coralogix-aws/pull/175
