### ISSUE TITLE
Allow setting lambda runtime for further flexibility

### ISSUE THREAD

**Issue by osherdp** [coralogix/terraform-coralogix-aws#168]
As of now, it's not possible to set the lambda's runtime via the module, as it's currently hardcoded as `provided.al2023`:
https://github.com/coralogix/terraform-coralogix-aws/blob/76e4804a1de0fb124fa23b6c098635e2030a99c3/modules/coralogix-aws-shipper/main.tf#L43

Problem is, for some regions this runtime is not available. For example, on cn-north-1 (via `amazon.cn`) it currently says:
```
module.coralogix-shipper-s3.module.lambda["integration"].aws_lambda_function.this[0]: Creating...
╷
│ Error: creating Lambda Function (Coralogix-S3-50wIns): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: 96913980-6ebe-4558-931f-5d1dadd2740d, InvalidParameterValueException: Value provided.al2023 at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [provided.al2, java8.al2, java17, ruby3.2, nodejs16.x, python3.8, python3.9, python3.10, java11, python3.11, dotnet6, nodejs18.x] or be a valid ARN
│
│   with module.coralogix-shipper-s3.module.lambda["integration"].aws_lambda_function.this[0],
│   on .terraform/modules/coralogix-shipper-s3.lambda/main.tf line 24, in resource "aws_lambda_function" "this":
│   24: resource "aws_lambda_function" "this" {
```

**Comment by osherdp** [comment]
@royfur @guyrenny I took the liberty of implementing this feature, please take a look at the linked pull-request 🙏

**Comment by guyrenny** [comment]
Hi @osherdp , thank you for letting us know about this issue, unfortunately, the lambda currently is not working for a runtime that is not `provided.al2023`, the changes that will need to be made are in the source code ([coralogix-aws-shipper](https://github.com/coralogix/coralogix-aws-shipper)) and not only to the terraform. We are looking for a solution for this issue and i will make sure to keep you updated

**Comment by osherdp** [comment]
> Hi @osherdp , thank you for letting us know about this issue, unfortunately, the lambda currently is not working for a runtime that is not `provided.al2023`, the changes that will need to be made are in the source code ([coralogix-aws-shipper](https://github.com/coralogix/coralogix-aws-shipper)) and not only to the terraform. We are looking for a solution for this issue and i will make sure to keep you updated

`provided.al2` doesn't work?

**Comment by guyrenny** [comment]
> > Hi @osherdp , thank you for letting us know about this issue, unfortunately, the lambda currently is not working for a runtime that is not `provided.al2023`, the changes that will need to be made are in the source code ([coralogix-aws-shipper](https://github.com/coralogix/coralogix-aws-shipper)) and not only to the terraform. We are looking for a solution for this issue and i will make sure to keep you updated
> 
> `provided.al2` doesn't work?

Not at the moment
