### ISSUE TITLE
Issue with CloudWatch groups in Coralogix AWS Shipper

### ISSUE THREAD

**Issue by rudolf-repcin** [coralogix/terraform-coralogix-aws#179]
Hello, I'm getting this error when trying to use latest Coralogix AWS Shipper module:

```
Error: reading CloudWatch Logs Log Group (/aws/vendedlogs/states/xxxxxxx-logs): empty result
│ 
│   with module.......xxxxxxxxxxxxxx........module.coralogix-shipper-cloudwatch.data.aws_cloudwatch_log_group.this["/aws/vendedlogs/states/xxxxxxx-logs"],
│   on .terraform/modules/.................coralogix-shipper-cloudwatch/modules/coralogix-aws-shipper/data.tf line 10, in data "aws_cloudwatch_log_group" "this":
│   10: data "aws_cloudwatch_log_group" "this" {
```

I'm using following versions:
- Terraform v1.9.5
- Coralogix provider v1.18.6
- Coralogix AWS Shipper module 1.0.108
- AWS Terraform provider v5.67.0

This is happening during "terraform init" phase and fails completely. I don't have any of these resources yet created - I have deleted them all before.

The issue is not happening for other log shipper of the same version. Issue probably happened after I restructured my Terraform so it had to delete all resources and re-create them back.

Update: When I removed the shipper from Terraform, let the plan apply and then re-added the shipper, it passed.

**Comment by rudolf-repcin** [comment]
Hello, I guess this can be re-opened, I wasn't sure if this is a temporary issue or not but I can still see it occuring.

**Comment by guyrenny** [comment]
Hey @rudolf-repcin, can you share your configuration so I can try and see what could be the issue?
When I tried to deploy the integration with a log group that doesn't exist I got the same error that you got, so if you could first try to validate the log group that you tried to pass to the integration and make sure that the name is correct, and that it's in the same region as you try to deploy the integration in.
Another thing is that it is kind of weird that you got this error during `terraform init` and not in `terraform plan/apply`, do you have other modules or resources that you run with our module that could be connected?

**Comment by rudolf-repcin** [comment]
Hello, sorry for that, it's terraform plan not init. My configuration is kind of complex - however I tried this on a different environment and it passed. So it must have been something to do with my terraform state. Log group was definitely in the same region and account, also the name was fine.

The thing is - I have restructured my Terraform plan a bit so all resources tried to re-create themselves, that's when it happened - after all resources got deleted. However I removed the shipper, ran the plan, then re-added the shipper and it works.

**Comment by guyrenny** [comment]
Do you try to create the log groups as part of your terraform and then pass them to the module? If so, do you also have a random string in the log group name?
What do you mean by **_tried this on a different environment_**? different coralogix or AWS environment
Maybe you could only share your coralogix module so I could try to duplicate the issue

**Comment by rudolf-repcin** [comment]
By different environemnt - I meant different AWS environment.

This is shortened configuration I'm using. Now I tried it second time - move the resources in a directory structure - and it happened again. Terraform destroyed the resources and when it started creating them - the error with empty result happened.

```terraform
resource "aws_cloudwatch_log_group" "snapshot_state_machine_logs" {
  name              = "/aws/vendedlogs/states/${local.snapshot_state_machine_name}-logs"
  retention_in_days = 1
  skip_destroy      = false
  tags = {
    Name = "${var.aws_account_name}-snapshot-state-machine-cw-log-group"
  }
}

module "coralogix-shipper-cloudwatch" {
  source = "github.com/coralogix/terraform-coralogix-aws//modules/coralogix-aws-shipper?ref=v1.0.108"

  # General configuration
  integration_type                 = "CloudWatch"
  coralogix_region                 = "EU2"
  api_key                          = var.coralogix_api_key
  store_api_key_in_secrets_manager = false # temporary

  application_name = var.aws_account_name
  subsystem_name = "xxx"

  # CloudWatch configuration
  log_groups = [aws_cloudwatch_log_group.snapshot_state_machine_logs.name]

  # Lambda configuration
  lambda_name          = "xxx-logs-coralogix-shipper"
  memory_size          = 848
  lambda_log_retention = 1
  log_level            = var.lambda_log_level
  cpu_arch             = "arm64"
  runtime              = "provided.al2023"
  tags = {
    Name = "${var.aws_account_name}-xxx-logs-coralogix-shipper-lambda"
  }
}

resource "aws_cloudwatch_log_resource_policy" "xxx_log_policy" {
  policy_name     = "xxx-logging-policy"
  policy_document = data.aws_iam_policy_document.xxx_log_policy_document.json
}

data "aws_iam_policy_document" "xxx_log_policy_document" {
  statement {
    sid    = "AWSLogDeliveryWrite"
    effect = "Allow"
    principals {
      type = "Service"
      identifiers = ["delivery.logs.amazonaws.com"]
    }
    actions = [
      "logs:PutLogEvents",
      "logs:CreateLogStream"
    ]
    resources = ["${aws_cloudwatch_log_group.snapshot_state_machine_logs.arn}:*"]
    condition {
      test     = "ArnLike"
      variable = "aws:SourceArn"
      values = ["arn:aws:logs:eu-central-1:${var.aws_account_id}:*"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"
      values = [var.aws_account_id]
    }
  }
}
```

**Comment by rudolf-repcin** [comment]
I would assume that Terraform will create this log group before CX shipper is created so I haven't added explicit dependency to the CW log group. Probably it's needed for some reason.

**Comment by guyrenny** [comment]
I also tried to run a similar setup to what you have, and I did get the same error, this happens because in the shipper module, we need to read the log groups that you will provide, in case the module still doesn't know the name of the log group or it doesn't exist then you would get this error.
When I added depend on for the log group resource it solved the issue, so if you could try and add: `depends_on = [aws_cloudwatch_log_group.snapshot_state_machine_logs]` in the coralogix-shipper-cloudwatch module, it should fix your problem.

**Comment by rudolf-repcin** [comment]
Yes, I already did and it resolved it. However I would assume that log group would create automatically before the module needs it. Not sure why this isn't happening. I am providing the resource name to the module so Terraform should detect that and create log group before. Anyway, thanks for assistance.

**Comment by guyrenny** [comment]
Sure happy to help, I agree with you it is weird that Terraform doesn't know how to handle it, but at least we have a solution for it.
