### ISSUE TITLE
Terraform v1.10.0 breaks module coralogix-aws-shipper 

### ISSUE THREAD

**Issue by dennischristmann** [coralogix/terraform-coralogix-aws#186]
Hey guys,

the newest version of terraform breaks one of your modules:

> │   on ..../modules/coralogix-aws-shipper/main.tf line 284, in resource "aws_secretsmanager_secret" "coralogix_secret":
> │  284:   for_each = {
> │  285:     for key, integration_info in var.integration_info != null ? var.integration_info : local.integration_info : key => integration_info
> │  286:     if !local.api_key_is_arn && (integration_info.store_api_key_in_secrets_manager == null || integration_info.store_api_key_in_secrets_manager == true) 
> │  287:   }
> │     ├────────────────
> │     │ local.api_key_is_arn has a sensitive value
> │     │ local.integration_info is map of object with 1 element
> │     │ var.integration_info is null

It's caused. because local.api_key_is_arn  is derived from the  sensitive var.api_key .  Probably all to change is to add a call to the nonsensitive function when creating api_key_is_arn

  api_key_is_arn = replace(var.api_key, ":", "") != var.api_key ? true : false

  api_key_is_arn = nonsensitive(replace(var.api_key, ":", "") != var.api_key ? true : false)

Best regards,
Dennis

**Comment by guyrenny** [comment]
Hey @dennischristmann, I have merged a [PR](https://github.com/coralogix/terraform-coralogix-aws/pull/191) that will fix this issue and allow you to run the module with terraform version 1.10.0. Let me know if you still have issues deploying the integration.

**Comment by dennischristmann** [comment]
Hey @guyrenny ,

I can confirm: Terraform v1.10.3 and coralogix-aws-shipper v2.3.1 work well together.

Thanks!
Dennis

**Comment by dennischristmann** [comment]
Fixed in v2.3.1
