### ISSUE TITLE
firehose-logs: LogDeliveryEnabled tag missing for aws_kinesis_firehose_delivery_stream resource

### ISSUE THREAD

**Issue by K-Nakul-K** [coralogix/terraform-coralogix-aws#194]
Missing LogDeliveryEnabled = true tag for aws_kinesis_firehose_delivery_stream resource. 
When applying module again, LogDeliveryEnabled tag gets removed since its not from Terraform but from AWS (aws adds it at the time of creation). 

`
~ resource "aws_kinesis_firehose_delivery_stream" "coralogix_stream_logs" {
      id             = "arn:aws:firehose:us-east-1:746657877466:deliverystream/test-74665787-firewall-firehose-logs-stream"
      name           = "test-74665787-firewall-firehose-logs-stream"
    ~ tags           = {
        - "LogDeliveryEnabled"       = "true" -> null
          # (4 unchanged elements hidden)
      }
    ~ tags_all       = {
        - "LogDeliveryEnabled"       = "true" -> null
          # (16 unchanged elements hidden)
      }
      # (4 unchanged attributes hidden)
      # (2 unchanged blocks hidden)
  }
`

**Comment by ryantanjunming** [comment]
@K-Nakul-K can i have the aws documentation mentioning this `LogDeliveryEnabled` tag provided?
