### ISSUE TITLE
Bug in https://github.com/coralogix/terraform-coralogix-aws/blob/master/modules/s3/main.tf

### ISSUE THREAD

**Issue by billhammond-dev** [coralogix/terraform-coralogix-aws#55]
The logger library assumes that the env var coralogix_url is capitalized, i.e. CORALOGIX_URL in the env config of the lambda function.
I can only get this module's lambda to work if I capitalize the env var so the logger picks up the correct url endpoint

in coralogix-logger/dist/constants.js:

Constants.CORALOGIX_LOG_URL = process.env.CORALOGIX_URL || Constants.PROD_URL;

Hence the env var for the function needs to be CORALOGIX_URL
Please change line 65 in main.tf to match. Thanks.

**Comment by guyrenny** [comment]
Update coralogix_url to be CORALOGIX_URL in this PR - (https://github.com/coralogix/terraform-coralogix-aws/pull/57)
