### ISSUE TITLE
cloudwatch-logs module lambda with ssm_enable = "True" is missing the wrapper.sh script needed to function

### ISSUE THREAD

**Issue by billhammond-dev** [coralogix/terraform-coralogix-aws#70]
From what I have read in the aws docs it would need to be in your folder/repo somewhere and added as a layer.

**Comment by guyrenny** [comment]
The wrapper.sh is in our [serverless repo ](https://github.com/coralogix/coralogix-aws-serverless/tree/master/src/lambda-secretLayer), also you can create the layer from our [Coralogix-Lambda-SSMLayer](https://eu-central-1.console.aws.amazon.com/lambda/home#/create/app?applicationId=arn:aws:serverlessrepo:eu-central-1:597078901540:applications/Coralogix-Lambda-SSMLayer).
